baseURL = "https://mandelbrotz.com"
theme = 'hugo-bearblog'

title = "ฅ՞•ﻌ•՞ฅ Mandelbrot’z"
author = "John Doe"
copyright = "Copyright © 2023-2025, Mandelbrot."
languageCode = "en-US"

enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
blog = "/:slug/"
tags = "/blog/:slug"

[params]
description = "Maple world deep diver"
favicon = "images/favicon.png"
images = ["images/share.png"]
title = "Hugo ฅ՞•ﻌ•՞ฅ Bear"
hideMadeWithLine = false
disqusShortname = "https-mandelbrotz-com"

[params.Author]
email = "lichtung_nitro@outlook.com"

[params.RSS]
enableRSS = true

[params.Footer]
hideRSSAndEmail = false
hideMadeWithLine = false
hideCopyright = false
hideSitemap = false

[markup]
[markup.highlight]
style = 'github'
lineNos = false
lineNumbersInTable = false
codeFences = true

[markup.goldmark.renderer]
unsafe = true
