baseURL = "https://mandelbrotz.com"
theme = 'hugo-bearblog'

title = "mandelbrot."
author = "John Doe"
copyright = "Copyright Â© 2023-2025, Mandelbrot."
languageCode = "en-US"

enableRobotsTXT = true
enableGitInfo = false

# Sitemap configuration
[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
blog = "/:slug/"
tags = "/blog/:slug"

[params]
description = "Maple world deep diver"
favicon = "images/favicon.png"
images = ["images/share.png"]
hideMadeWithLine = false
disqusShortname = "https-mandelbrotz-com"
titleFormat = "{{ .Title }}"
disableTitlePrefix = true
pageTitle = "{{ .Title }}"

[params.Author]
email = "lichtung_nitro@outlook.com"

[params.RSS]
enableRSS = true

[params.Footer]
hideRSSAndEmail = false
hideMadeWithLine = false
hideCopyright = false
hideSitemap = false

[markup]
[markup.highlight]
style = 'github'
lineNos = false
lineNumbersInTable = false
codeFences = true

[markup.goldmark.renderer]
unsafe = true
